pipeline {                       //must be top level
   agent any                     //agent -> where to execute like jenkinscluster , windows node like
   stages {
     stage("build") {
       steps {
         //sh 'npm install'      //if you run java based appn use npm 
         //sh 'npm build'
         echo 'build appication'
       }
     }
     stage("test") {
       steps {
         echo 'test appication'
       }
     }
     stage("deploy") {
       steps {
         echo 'deploy appication'       
       }
     }
  }
}



------------------------jenkins file2----------------------------------
   
https://github.com/vinodkumar501/itrack-jenkinsfile-learning-repo.git
   
pipeline {
    agent any
    tools {
        maven 'mvn-3.8.4'
    }
    stages {
        stage ('Compile Stage') {
            steps {
                    sh 'mvn clean compile'
                }
            }
        stage ('Testing Stage') {

            steps {
                    sh 'mvn test'
                }
            }
        stage ('Deployment Stage') {
            steps {
                    sh 'mvn deploy'
                }
            }
        }
    }
